### ISSUE TITLE
Could not load commands from plugin plugins/test

### ISSUE THREAD

**Issue by crydotsnake** [Sebobo/Shel.Neos.CommandBar#20]
![SCR-20230203-j7k](https://user-images.githubusercontent.com/39345336/216607621-991d524c-62a2-435a-8451-e9ac23cae08a.png)

It does not affect the functionality of the package. But I still wanted to point out.

**Comment by Sebobo** [comment]
I close this for now until there are more details.

**Comment by crydotsnake** [comment]
> Browser and Neos version?

Whoops. I totall missed this.

Browser was Google Chrome, and Neos version was the dev version from the `neos-development-collection`

**Comment by Sebobo** [comment]
OK that is hard to debug then 🤪
If you can reproduce with 8.2 then feel free to reopen.
