### ISSUE TITLE
Add one line explaining the plugin types

### ISSUE THREAD

**Issue by alexander-nitsche** [Sebobo/Shel.Neos.CommandBar#42]
**Is your feature request related to a problem? Please describe.**
As a semi-new Neos CMS user, I have been reading the documentation and code files of your package to learn how to write modern Neos packages. Your documentation and coding style is very clean, readable and thus suitable as a showcase for others, thanks for that! Only at one point I couldn't follow your README instructions, namely where you mention two plugin types (Neos UI and module): it's probably clear for more experienced Neos users what you're talking about, but for me an additional sentence about the purpose of the two plugin contexts would be helpful. Are both used in conjunction or is only one type used in a Neos instance?

**Describe the solution you'd like**
An additional sentence explaining the plugin types in the README would be helpful for newcomers.

**Describe alternatives you've considered**
Ignoring the plugin types section for now, moving forward in Neos knowledge and understanding plugin types in a larger context would also be an alternative:)

**Additional context**
None.

**Comment by Sebobo** [comment]
Thx for the input! I will add more details.

**Comment by alexander-nitsche** [comment]
Nice explanation, thanks!
